### ISSUE TITLE
First assets

### ISSUE THREAD

**Issue by Ilistratov** [Ilistratov/LostInTheDark#12]
На(воро)рисовать спрайты для объетов. На первое время нужны

- стенки
- дверь
- светильник/фонарик/ect
- ключ

Камера смотрит на карту сверху. При этом видны все 4 стены.(так-же как в binding of isaac)

**Comment by Sokolok003** [comment]
![LampVersion1](https://user-images.githubusercontent.com/49098530/143776331-e63e6a07-58d2-4f01-b2ed-bc920926b417.png)

**Comment by Sokolok003** [comment]
![pixil-frame-0 (3)](https://user-images.githubusercontent.com/49098530/143776744-c4ca690f-3c6e-4379-9f05-57ebbd6f6336.png)

**Comment by Sokolok003** [comment]
![pixil-frame-0 (4)](https://user-images.githubusercontent.com/49098530/143778491-0f860917-e4bb-4953-a1fd-457888f123ab.png)

**Comment by Sokolok003** [comment]
![pixil-frame-0 (8)](https://user-images.githubusercontent.com/49098530/143780732-b782c053-3385-49f1-af06-d74f36e41578.png)

Возможная дверь, если будут кат-сцены

**Comment by Sokolok003** [comment]
![pixil-gif-drawing (1)](https://user-images.githubusercontent.com/49098530/143781137-992a6331-6a50-4f0c-9256-5d96c9cd2075.gif)
![Pixilart Sprite Sheet](https://user-images.githubusercontent.com/49098530/143781191-54b2384c-4b81-4114-aa3a-1a9d611657a3.png)
Фонарь гг

**Comment by Sokolok003** [comment]
![pixil-frame-0 (11)](https://user-images.githubusercontent.com/49098530/144261590-cbe57be6-50a0-4735-b8fa-3044aaa6aba3.png)
Внешка пространства (пример комнаты)

**Comment by Sokolok003** [comment]
![pixil-gif-drawing (3)](https://user-images.githubusercontent.com/49098530/144261619-1540dd02-e9df-4b6c-b0a2-bb82959bbfca.gif)

Интерьер в виде черепа со свечей

**Comment by Sokolok003** [comment]
![pixil-frame-0 (12)](https://user-images.githubusercontent.com/49098530/144262904-c8a80c58-2960-47fe-bdc9-de763715ced7.png)

Пример комнаты с дверьми

**Comment by Sokolok003** [comment]
Измененный интерьер, так как неправильно выделял тайлы

![pixil-frame-0 (15)](https://user-images.githubusercontent.com/49098530/144281988-bb59c75c-4f9a-4a13-a927-bfdf79669d9d.png)

**Comment by Sokolok003** [comment]
Пример с дверью и окном
![pixil-frame-0 (14)](https://user-images.githubusercontent.com/49098530/144277443-ad6dbe44-9495-4073-9914-622974ee854f.png)

**Comment by Sokolok003** [comment]
![pixil-frame-0 (17)](https://user-images.githubusercontent.com/49098530/144289066-47a4c708-e288-424c-bb9f-d9d8b11b337d.png)

Все части для составления карты

**Comment by Ilistratov** [comment]
Норм, на первое время хватит. Запихни стенки/пол/двери в тайлсет, остальное в обычные спрайты и создай пр.

Алсо я думаю, нам будет нужно больше тайлов со стенами для разных позициый, с которых на них
будет смотреть игрок. Примерно как на картинке ниже. Там 9 различных позиций для ситуаций, когда обе части
угла видны. На самом деле там суммарно должно быть ~25 вариаций одной и той-же стенки с разных углов.
Видимо руками это все делать будет смертельно неудобно, надо будет подумать, как этот процесс автоматизировать.
Скорее всего придется прибегнуть к магии 3D, но это уже в другой задаче.

![image](https://user-images.githubusercontent.com/37190820/144298570-cabd3cc0-caa9-484f-a026-cb23563b07f0.png)

**Comment by Sokolok003** [comment]
all done
