### ISSUE TITLE
2D lighting

### ISSUE THREAD

**Issue by Ilistratov** [Ilistratov/LostInTheDark#14]
В общих чертах понять и описать, как работает 2d освещение в пакете, который упоминал @MonsterOnLeash на последнем
созвоне. Что удасться узнать отписать в коменты к этой issue. + завести задачки на создание объектов, взаимодействующих
со светом(для начала - источник света и обобщенный компонент, который следит за уровнем освещенности в текущей позиции.)

**Comment by MonsterOnLeash** [comment]
https://www.youtube.com/watch?v=nkgGyO9VG54
universal render pipeline (universal rp)

**Comment by MonsterOnLeash** [comment]
As far as I have learnt, there is no way to make player not leave the light using only methods of URP. However, we can use raycast to check if there are collision objects in-between the source of light and the object. By that the same effect should be achieved.

**Comment by Ilistratov** [comment]
Для освещения будем использовать URP и 2D источники освещения. Они достаточно хорошо описаны тут:
https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@13.1/manual/LightTypes.html#sprite

Для нужд игровой логики совещенность предмета будем проверять с помощью Raycast. Он описан тут:
https://docs.unity3d.com/ScriptReference/Physics.Raycast.html

Такое решение потребует для каждого объекта, отбрасывающего тень, добавлять компонент collider и shadow caster 2d
(описан тут: https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@13.1/manual/2DShadows.html)
Думаю, это все довольно удобно запихнуть в префабы.
