### ISSUE TITLE
Create light interactor component

### ISSUE THREAD

**Issue by MonsterOnLeash** [Ilistratov/LostInTheDark#23]
Component which will check if an object is lighted or not

**Comment by Ilistratov** [comment]
Как раз хотел таку задачку завести. Видимо для каждого источника света ты будешь с помощью Physics.Raycast проверять, долетает ли свет до текущего объекта. Возможно в #14 ты найдешь для себя какую-нибудь полезную информацию.

**Comment by MonsterOnLeash** [comment]
Also URP is applied to the project and scratch light source prefab added
