### ISSUE TITLE
Wall/Light colliders

### ISSUE THREAD

**Issue by Ilistratov** [Ilistratov/LostInTheDark#29]
Сделать так, чтобы свет блокировался стенами.

**Comment by MonsterOnLeash** [comment]
So one of most basic ways is to create empty objects for every wall that would cast shadows. It is the simpliest thing from theoretical point of view and the most painful idea as for big rooms we'll need to battle with creating a shadow caster object for each wall. However, this way seems o me the most flexible as in case we want to make a differently shaped shadow (for example to make some inner-conner not to cast shadow so the player can get a clue that there is some object hidden in the wall)
