### ISSUE TITLE
Player death on moving through door without lantern

### ISSUE THREAD

**Issue by Ilistratov** [Ilistratov/LostInTheDark#49]
Нужно придумать что-то, что предотвращает смерть игрока в случае, когда тот забыл взять с собой
фонарь при попытке пройти через дверь.
На пример, дать каждой двери слабый источник света, который активируется, когда игрок в первый раз
подходит к двери.

**Comment by Sokolok003** [comment]
Вот кстати на счет источников света для двери это приколдесно. Можно просто включать свет, когда дверь разблокируется
